#!/bin/bash


pUsage()
{
cat <<EOF
 Usage is :
 echo  "Wrong Usage ...."
                echo "Usage is TestJdbc_ksh db_host instance user pass rac/na"
                
                echo "For testing RAC     : TestJdbc_ksh servr20 SERVICE99_TAF admin admin rac"
                echo "For testing Non_rac : TestJdbc_ksh server80 INSTSM3 admin admin na"
EOF
}


if [[ $# -ne 5 ]]; then
        pUsage
        exit;
fi

#########PLEASE POINT TO OJDBC6.JAR

export CLASSPATH=${CLASSPATH}:/usr/jdbc_test/ojdbc6.jar

#######
cd /location_to_classfile/jdbc_test/
######

java testJdbc $@
