#!/bin/ksh


printUsage()
{
cat <<EOF
 Usage is :
 echo  "Wrong Usage ...."
                echo "Usage is TestJdbc_ksh db_host instance user pass rac/na"
                
                echo "For testing RAC     : TestJdbc_ksh illin574v PNTCRMR_TAF sa sa rac"
                echo "For testing Non_rac : TestJdbc_ksh illin1180 PI90ASM3 sa sa na"
EOF
}


if [[ $# -ne 5 ]]; then
        printUsage
        exit;
fi

#########PLEASE POINT TO OJDBC6.JAR

export CLASSPATH=${CLASSPATH}:/usr/jdbc_test/ojdbc6.jar

#######
cd /location_to_classfile/jdbc_test/
######

java testJdbc $@
